customer_name: bso
odoo_version: '10.0'
customer_shortname: bso
repo_name: bso
project_id: '1882'
project_name: bso_odoo
odoo_company_name: BSO Network Solutions
odoo_main_lang: fr_FR
odoo_aux_langs: 
