{
    'name': 'BSO custom doc',
    'description': 'Customize BSO documents: order forms, invoices',
    'author': 'BSO',
    'website': 'https://www.bsonetwork.com',
    'depends': ['base',
                'sale',
                'product',
                'sale_stock',
                'website_quote',
                'website_sale',
                'account_payment_sale',
                ],
    'data': [
        'security/ir.model.access.csv',
        'views/custom_layout.xml',
        'views/sale_order.xml',
        'views/res_partner.xml',
        'views/product_category.xml',
        'views/report_sale_order.xml',
    ],
    'css': ['static/src/css/style.css'],
    'application': False,
}
